[package]
name = "Team_Work_Lambert_w_function"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
anyhow = "1.0.96"
env_logger = "0.11.6"
log = "0.4.26"
structopt = "0.3.26"
thiserror = "2.0.11"
=======
structopt = "0.3"
thiserror = "1.0"

[[bin]]
name = "Team_Work_Lambert_w_function"
path = "src/main.rs"

[lib]
name = "Team_Work_Lambert_w_function"
path = "src/lib.rs"
>>>>>>> write
