name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 
  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Grant permission to write to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/onelrian/lambert_w_function:sha-${{ github.sha }}
            ghcr.io/onelrian/lambert_w_function:branch-${{ github.ref_name }}
            ghcr.io/onelrian/lambert_w_function:latest